In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import pandas as pd
import numpy as np
import re

In [43]:
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("start-maximized")
options.add_argument("--disable-infobars")
driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
URL='https://www.ocasionplus.com/coches-ocasion?utm_source=GoogleSearch&utm_medium=cpc&utm_campaign=Search_%7c_Madrid_%7c_Venta_%7c_Coches&utm_term=coche%20segunda%20mano&gclid=CjwKCAjwmf_4BRABEiwAGhDfSYckXbroGla3C8T2IsHgJ_YPGr9_xn3xWo0Vw8YlfI7OT5FYrO2YGRoCy-kQAvD_BwE&gclsrc=aw.ds'
driver.get(URL)

In [44]:
precio= driver.find_elements_by_xpath('//*[@id="__next"]/div[1]/div[1]/div[2]/div[2]/div/div[2]')
precio

In [45]:
cochesBuenos= [e.text for e in precio]
cochesBuenos

['ZARAGOZA\nPeugeot 307 SW 1.6 HDI Port Aventura (110 CV)\n1.200€\n02/2005291.513 kmDiéselManual\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nCOLLADO-VILLALBA\nPeugeot 206 CC Cabrio 1.6 (110CV)\n4.700€\n03/2006103.502 kmGasolinaManual\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nCOLLADO-VILLALBA\nAudi A4 1.8 (125 CV)\n900€\n07/1997163.778 kmGasolinaManualÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nCOLLADO-VILLALBA\nRenault Modus 1.2 16v Emotion (75CV)\n4.500€\n01/200877.058 kmGasolinaManualÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-664€\nCOLLADO-VILLALBA\nFiat Panda 1.2 Lounge EU6 (69 CV)\n6.636€\n7.300€\nDesde 75€/mes\na 10 años\n01/201834.792 kmGasolinaManualLibro MantenimientoÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-1927€\nSEVILLA\nNissan X-Trail 1.6 dCi N-Connecta (130 CV)\n19.273€\n21.200€\nDesde 256€/mes\na 10 años\n04/201828.374 kmDiéselManual\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nZARAGOZA\nSkoda Yeti 1.2 TSI Ambition 4x2 (105 CV)\n8.950€\nDesde 146€/mes\na 6 años\n07/201399.067 kmGasolinaManualLibro MantenimientoÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-1218€\nCOLLADO-VILLALBA\nSsangyong Tivoli G16 Premium 4x2 (128 CV)\n12.182€\n13.400€\nDesde 164€/mes\na 9 años\n02/201751.879 kmGasolinaManual\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-1800€\nCOLLADO-VILLALBA\nMazda CX-3 2.0 G Zenith 2WD AT 4x2 (121 CV)\n18.000€\n19.800€\nDesde 238€/mes\na 10 años\n08/201915.831 kmGasolinaAutomáticoÚnico propietarioGarantía oficial: Agosto 2020\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-1591€\nCOLLADO-VILLALBA\nRenault Grand Scenic dCi 110 Zen 7 Plazas (110 CV)\n15.909€\n17.500€\nDesde 221€/mes\na 9 años\n06/201792.241 kmDiéselManualÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nCOLLADO-VILLALBA\nFord Mondeo 2.0 TDCi Futura X (130CV)\n2.300€\n10/2005158.797 kmDiéselManualLibro Mantenimiento\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nIVA DEDUCIBLE\nBARCELONA-TARRASA\nJaguar F-Pace 2.0T i4 Prestige AWD Auto (250 CV)\n43.182€\n47.500€\nDesde 598€/mes\na 10 años\n02/202018 kmGasolinaAutomáticoÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-886€\nSEVILLA\nRenault Clio Limited Energy TCe (90 CV)\n8.864€\n9.750€\nDesde 114€/mes\na 9 años\n04/201741.012 kmGasolinaManual\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nZARAGOZA\nOpel Insignia Sports Tourer Sports Tourer 2.0 CDTI EcoFlex Sport (160CV)\n8.750€\nDesde 244€/mes\na 3 años\n01/2011103.480 kmDiéselManualLibro Mantenimiento\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-2782€\nVALENCIA-PATERNA\nAudi A5 Sportback 1.4 TFSI S tron Sportback (150CV)\n27.818€\n30.600€\nDesde 379€/mes\na 10 años\n01/20185.490 kmGasolinaAutomático\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nBILBAO-BASAURI\nMercedes-Benz Clase E 320 CDI Avantgarde (204CV)\n8.450€\n05/2003119.737 kmDiéselAutomáticoLibro Mantenimiento\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-1409€\nBARCELONA-TARRASA\nOpel Zafira 1.4 Turbo S&S Selective 7 Plazas (140 CV)\n14.091€\n15.500€\nDesde 182€/mes\na 10 años\n07/20178.010 kmGasolinaManualLibro MantenimientoÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nSEVILLA\nOpel Astra 1.7 CDTi GTC Cosmo (100CV)\n4.400€\n07/200892.568 kmDiéselManualÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\nVALENCIA-ALZIRA\nFord Focus C-Max 1.6 Trend (100 CV)\n3.900€\n02/200590.388 kmGasolinaManualLibro MantenimientoÚnico propietario\nContactar\nVER DE UN VISTAZO\nCOMPARAR\n-1682€\nVALENCIA-PATERNA\nMazda CX-3 1.5 DE SKYACTIV Luxury White Travel 4WD (105 CV)\n16.818€\n18.500€\nDesde 221€/mes\na 10 años\n08/201736.308 kmDiéselAutomático\nContactar\nVER DE UN VISTAZO\nCOMPARAR']

In [46]:
for e in cochesBuenos:
    ok=e.split("\n")
ok

['ZARAGOZA',
 'Peugeot 307 SW 1.6 HDI Port Aventura (110 CV)',
 '1.200€',
 '02/2005291.513 kmDiéselManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Peugeot 206 CC Cabrio 1.6 (110CV)',
 '4.700€',
 '03/2006103.502 kmGasolinaManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Audi A4 1.8 (125 CV)',
 '900€',
 '07/1997163.778 kmGasolinaManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Renault Modus 1.2 16v Emotion (75CV)',
 '4.500€',
 '01/200877.058 kmGasolinaManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-664€',
 'COLLADO-VILLALBA',
 'Fiat Panda 1.2 Lounge EU6 (69 CV)',
 '6.636€',
 '7.300€',
 'Desde 75€/mes',
 'a 10 años',
 '01/201834.792 kmGasolinaManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1927€',
 'SEVILLA',
 'Nissan X-Trail 1.6 dCi N-Connecta (130 CV)',
 '19.273€',
 '21.200€',
 'Desde 256€/mes',
 'a 10 años',
 '04/201828.374 kmDiéselManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Skoda Yeti 1.2 TSI Ambition 4x2 (105 CV)',
 '8.950€',
 'Desde 146€/mes',
 'a 6 años',
 '07/201399.067 kmGasolinaManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1218€',
 'COLLADO-VILLALBA',
 'Ssangyong Tivoli G16 Premium 4x2 (128 CV)',
 '12.182€',
 '13.400€',
 'Desde 164€/mes',
 'a 9 años',
 '02/201751.879 kmGasolinaManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1800€',
 'COLLADO-VILLALBA',
 'Mazda CX-3 2.0 G Zenith 2WD AT 4x2 (121 CV)',
 '18.000€',
 '19.800€',
 'Desde 238€/mes',
 'a 10 años',
 '08/201915.831 kmGasolinaAutomáticoÚnico propietarioGarantía oficial: Agosto 2020',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1591€',
 'COLLADO-VILLALBA',
 'Renault Grand Scenic dCi 110 Zen 7 Plazas (110 CV)',
 '15.909€',
 '17.500€',
 'Desde 221€/mes',
 'a 9 años',
 '06/201792.241 kmDiéselManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Ford Mondeo 2.0 TDCi Futura X (130CV)',
 '2.300€',
 '10/2005158.797 kmDiéselManualLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'BARCELONA-TARRASA',
 'Jaguar F-Pace 2.0T i4 Prestige AWD Auto (250 CV)',
 '43.182€',
 '47.500€',
 'Desde 598€/mes',
 'a 10 años',
 '02/202018 kmGasolinaAutomáticoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-886€',
 'SEVILLA',
 'Renault Clio Limited Energy TCe (90 CV)',
 '8.864€',
 '9.750€',
 'Desde 114€/mes',
 'a 9 años',
 '04/201741.012 kmGasolinaManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Opel Insignia Sports Tourer Sports Tourer 2.0 CDTI EcoFlex Sport (160CV)',
 '8.750€',
 'Desde 244€/mes',
 'a 3 años',
 '01/2011103.480 kmDiéselManualLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-2782€',
 'VALENCIA-PATERNA',
 'Audi A5 Sportback 1.4 TFSI S tron Sportback (150CV)',
 '27.818€',
 '30.600€',
 'Desde 379€/mes',
 'a 10 años',
 '01/20185.490 kmGasolinaAutomático',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'BILBAO-BASAURI',
 'Mercedes-Benz Clase E 320 CDI Avantgarde (204CV)',
 '8.450€',
 '05/2003119.737 kmDiéselAutomáticoLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1409€',
 'BARCELONA-TARRASA',
 'Opel Zafira 1.4 Turbo S&S Selective 7 Plazas (140 CV)',
 '14.091€',
 '15.500€',
 'Desde 182€/mes',
 'a 10 años',
 '07/20178.010 kmGasolinaManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'SEVILLA',
 'Opel Astra 1.7 CDTi GTC Cosmo (100CV)',
 '4.400€',
 '07/200892.568 kmDiéselManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'VALENCIA-ALZIRA',
 'Ford Focus C-Max 1.6 Trend (100 CV)',
 '3.900€',
 '02/200590.388 kmGasolinaManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1682€',
 'VALENCIA-PATERNA',
 'Mazda CX-3 1.5 DE SKYACTIV Luxury White Travel 4WD (105 CV)',
 '16.818€',
 '18.500€',
 'Desde 221€/mes',
 'a 10 años',
 '08/201736.308 kmDiéselAutomático',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR']

In [36]:
droplist=['VER FICHA','SEMINUEVO','Al Contado:','Financiado:','Km0','KM.0','Manual','Automatica']
cleanList=[e for e in ok if e not in droplist]
cleanList

['BMW Serie 2',
 '228i Coupe 180kW (245CV)',
 '21.300€',
 '2015',
 '115.044 km',
 'Gasolina',
 '21.300 €',
 '22.900 €',
 'Mini Countryman',
 'Cooper 90 kW (122 CV)',
 '16.300€',
 '2016',
 '42.541 km',
 'Gasolina',
 '16.300 €',
 '17.900 €',
 'BMW Serie 1',
 '118d 110 kW (150 CV)',
 '32.900€',
 '2020',
 '3.000 km',
 'Diesel',
 '32.900 €',
 '32.900 €',
 'Mini Mini',
 'Cooper D 85 kW (116 CV)',
 '19.500€',
 '2017',
 '35.000 km',
 'Diesel',
 '19.500 €',
 '19.500 €',
 'Hyundai Tucson',
 'FL TGDI 1.6 177CV 4X2',
 '23.900€',
 '2020',
 'Gasolina',
 '23.900 €',
 '25.900 €',
 'Hyundai Santa Fe',
 '2.2 CRDI KLASS SR 2WD 200 5P 7 Plazas',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.990 €',
 '¡LIQUIDACIÓN BMW! hasta el 40% de descuento',
 'Hyundai Santa Fe',
 '2.2 CRDI KLASS SR 2WD 200 5P 7 Plazas',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.900 €',
 'Hyundai Santa Fe',
 'S.FE TM CRDI 2.2 200CV',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.900 €',
 'Hyundai i30',
 '1.0 TGDI N-LINE FASTBACK 120 5P',
 '17.990€',
 '2019',
 'Gasolina',
 '17.990 €',
 '19.990 €',
 'Hyundai Kona',
 '1.6 TGDI STYLE SKY RED DT 4WD 177 5P',
 '24.990€',
 '2020',
 'Gasolina',
 '24.990 €',
 '27.500 €',
 'Land Rover Range Rover Sport',
 '3.0 TDV6 HSE 190kW (258CV)',
 '37.900€',
 '2015',
 '100.848 km',
 'Diesel',
 'Cuota 742€/mes',
 '37.900 €',
 '39.900 €',
 'Mini Mini',
 'One D 70 kW (95 CV)',
 '16.300€',
 '2018',
 '22.499 km',
 'Diesel',
 'Cuota 243€/mes',
 '16.300 €',
 '17.900 €',
 '¡LIQUIDACIÓN BMW! hasta el 40% de descuento',
 'Página 1 de 63',
 '1',
 '2',
 '3',
 '4',
 '…',
 '63']

In [37]:
CleanList=[]

for e in cleanList:
    if not "¡LIQUIDACIÓN" in e:
             CleanList.append(e)       
CleanList

['BMW Serie 2',
 '228i Coupe 180kW (245CV)',
 '21.300€',
 '2015',
 '115.044 km',
 'Gasolina',
 '21.300 €',
 '22.900 €',
 'Mini Countryman',
 'Cooper 90 kW (122 CV)',
 '16.300€',
 '2016',
 '42.541 km',
 'Gasolina',
 '16.300 €',
 '17.900 €',
 'BMW Serie 1',
 '118d 110 kW (150 CV)',
 '32.900€',
 '2020',
 '3.000 km',
 'Diesel',
 '32.900 €',
 '32.900 €',
 'Mini Mini',
 'Cooper D 85 kW (116 CV)',
 '19.500€',
 '2017',
 '35.000 km',
 'Diesel',
 '19.500 €',
 '19.500 €',
 'Hyundai Tucson',
 'FL TGDI 1.6 177CV 4X2',
 '23.900€',
 '2020',
 'Gasolina',
 '23.900 €',
 '25.900 €',
 'Hyundai Santa Fe',
 '2.2 CRDI KLASS SR 2WD 200 5P 7 Plazas',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.990 €',
 'Hyundai Santa Fe',
 '2.2 CRDI KLASS SR 2WD 200 5P 7 Plazas',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.900 €',
 'Hyundai Santa Fe',
 'S.FE TM CRDI 2.2 200CV',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.900 €',
 'Hyundai i30',
 '1.0 TGDI N-LINE FASTBACK 120 5P',
 '17.990€',
 '2019',
 'Gasolina',
 '17.990 €',
 '19.990 €',
 'Hyundai Kona',
 '1.6 TGDI STYLE SKY RED DT 4WD 177 5P',
 '24.990€',
 '2020',
 'Gasolina',
 '24.990 €',
 '27.500 €',
 'Land Rover Range Rover Sport',
 '3.0 TDV6 HSE 190kW (258CV)',
 '37.900€',
 '2015',
 '100.848 km',
 'Diesel',
 'Cuota 742€/mes',
 '37.900 €',
 '39.900 €',
 'Mini Mini',
 'One D 70 kW (95 CV)',
 '16.300€',
 '2018',
 '22.499 km',
 'Diesel',
 'Cuota 243€/mes',
 '16.300 €',
 '17.900 €',
 'Página 1 de 63',
 '1',
 '2',
 '3',
 '4',
 '…',
 '63']

In [38]:
for e in range(7):
    CleanList.pop(-1)
CleanList

['BMW Serie 2',
 '228i Coupe 180kW (245CV)',
 '21.300€',
 '2015',
 '115.044 km',
 'Gasolina',
 '21.300 €',
 '22.900 €',
 'Mini Countryman',
 'Cooper 90 kW (122 CV)',
 '16.300€',
 '2016',
 '42.541 km',
 'Gasolina',
 '16.300 €',
 '17.900 €',
 'BMW Serie 1',
 '118d 110 kW (150 CV)',
 '32.900€',
 '2020',
 '3.000 km',
 'Diesel',
 '32.900 €',
 '32.900 €',
 'Mini Mini',
 'Cooper D 85 kW (116 CV)',
 '19.500€',
 '2017',
 '35.000 km',
 'Diesel',
 '19.500 €',
 '19.500 €',
 'Hyundai Tucson',
 'FL TGDI 1.6 177CV 4X2',
 '23.900€',
 '2020',
 'Gasolina',
 '23.900 €',
 '25.900 €',
 'Hyundai Santa Fe',
 '2.2 CRDI KLASS SR 2WD 200 5P 7 Plazas',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.990 €',
 'Hyundai Santa Fe',
 '2.2 CRDI KLASS SR 2WD 200 5P 7 Plazas',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.900 €',
 'Hyundai Santa Fe',
 'S.FE TM CRDI 2.2 200CV',
 '29.990€',
 '2019',
 'Diesel',
 '29.990 €',
 '31.900 €',
 'Hyundai i30',
 '1.0 TGDI N-LINE FASTBACK 120 5P',
 '17.990€',
 '2019',
 'Gasolina',
 '17.990 €',
 '19.990 €',
 'Hyundai Kona',
 '1.6 TGDI STYLE SKY RED DT 4WD 177 5P',
 '24.990€',
 '2020',
 'Gasolina',
 '24.990 €',
 '27.500 €',
 'Land Rover Range Rover Sport',
 '3.0 TDV6 HSE 190kW (258CV)',
 '37.900€',
 '2015',
 '100.848 km',
 'Diesel',
 'Cuota 742€/mes',
 '37.900 €',
 '39.900 €',
 'Mini Mini',
 'One D 70 kW (95 CV)',
 '16.300€',
 '2018',
 '22.499 km',
 'Diesel',
 'Cuota 243€/mes',
 '16.300 €',
 '17.900 €']

In [40]:
CleanList[0:7]

['BMW Serie 2',
 '228i Coupe 180kW (245CV)',
 '21.300€',
 '2015',
 '115.044 km',
 'Gasolina',
 '21.300 €']

In [31]:
model=CleanList[0::8]
model1=CleanList[1::8]
priceWithDiscount=CleanList[2::4]
cleanColumn=CleanList[3::4]
model

['BMW Serie 2',
 '22.900 €',
 '16.300 €',
 'Automatica',
 'Diesel',
 'Gasolina',
 'Diesel',
 'Diesel',
 'Diesel',
 'Gasolina',
 'Gasolina',
 '100.848 km',
 '16.300€']

In [ ]:
for e in cleanColumn:
    ok=e.split("\n")
cleanColumn2=[e.split("\n") for e in cleanColumn]
ok2=[]
for e in cleanColumn2:
    for i in e:
         ok2.append(i.split())
Año=[e[0] for e in ok2]

Año

In [ ]:
for e in cleanColumn:
    ok=e.split("\n")
cleanColumn2=[e.split("\n") for e in cleanColumn]
ok2=[]
for e in cleanColumn2:
    for i in e:
         ok2.append(i.split())
km=[e[2] for e in ok2]

km

In [ ]:
#Limpiando columna combustible
combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
combustiblesucio

In [ ]:
combustible=[item for sublist in combustiblesucio for item in sublist]
gas=[]

for e in combustible:
    if e == 'Hibrido':
        gas.append(e)
    elif e == "Diesel":
        gas.append(e)
    elif e == "Gasolina":
        gas.append(e)
    elif e == "Electrico":
        gas.append(e) 
gas

In [ ]:
cleanColumn

In [ ]:
df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })

In [ ]:
print(len(gas), len(Año), len(cleanColumn),len(model),len(priceWithDiscount),len(priceWithoutDiscount))

In [ ]:
df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
df1

In [ ]:
result = pd.concat([df, df1], axis=1, sort=False)
result

In [ ]:
flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
flexicar

In [ ]:
def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan
np_concat = np.vectorize(concat)
np_concat(flexicar['Ciudad'],flexicar['nan'])

In [ ]:
flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
flexicar

In [ ]:
flexicar = flexicar.drop(['nan'], axis=1)
flexicar

In [ ]:
# Tipos de usuarios:

Tipo1="https://www.flexicar.es/combustible-gasolina/carroceria-compacto/segunda-mano/"
Tipo2= "https://www.flexicar.es/combustible-gasolina/carroceria-turismo/segunda-mano/"
Tipo3= "https://www.flexicar.es/combustible-diesel/carroceria-turismo/segunda-mano/"
Tipo4= "https://www.flexicar.es/combustible-diesel/carroceria-familiar/segunda-mano/"
Tipo5= "https://www.flexicar.es/combustible-gasolina/carroceria-familiar/segunda-mano/"
Tipo6= "https://www.flexicar.es/combustible-gasolina/carroceria-monovolumen/segunda-mano/"
Tipo7= "https://www.flexicar.es/combustible-diesel/carroceria-monovolumen/segunda-mano/"
Tipo8= "https://www.flexicar.es/combustible-diesel/carroceria-furgoneta/segunda-mano/#plazas/8/"

In [ ]:
def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan

In [ ]:
def FlexicarScraping(tipo):
    #URL=f'https://www.flexicar.es/coches-segunda-mano/#precio_to/{presupuesto}/'
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("start-maximized")
    options.add_argument("--disable-infobars")
    driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    driver.get(tipo)
    precio= autos = driver.find_elements_by_xpath('//*[@id="listadocoches"]')
    cochesBuenos= [e.text for e in precio]
    for e in cochesBuenos:
        ok=e.split("\n")
    droplist=['Previous','Next',"IVA deducible"]
    cleanList=[e for e in ok if e not in droplist]
    CleanList=[]
    for e in cleanList:
        if not "desde" in e:
             CleanList.append(e)
    priceWithoutDiscount=CleanList[0::4]
    priceWithDiscount=CleanList[1::4]
    model=CleanList[2::4]
    cleanColumn=CleanList[3::4]
    for e in cleanColumn:
        ok=e.split("\n")
    cleanColumn2=[e.split("\n") for e in cleanColumn]
    ok2=[]
    for e in cleanColumn2:
        for i in e:
            ok2.append(i.split())
    Año=[e[0] for e in ok2]
    combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
    combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
    combustible=[item for sublist in combustiblesucio for item in sublist]
    gas=[]
    for e in combustible:
        if e == 'Hibrido':
            gas.append(e)
        elif e == "Diesel":
            gas.append(e)
        elif e == "Gasolina":
            gas.append(e)
        elif e == "Electrico":
            gas.append(e)
        elif e == "GLP":
            gas.append(e)
    df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })
    df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
    result = pd.concat([df, df1], axis=1, sort=False)
    flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
    def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan
    np_concat = np.vectorize(concat)
    flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
    flexicar = flexicar.drop(['nan'], axis=1)
    
    
    return flexicar.sort_values(by='Año', ascending=[True])

In [ ]:
def FlexicarScraping(tipo):
    #URL=f'https://www.flexicar.es/coches-segunda-mano/#precio_to/{presupuesto}/'
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("start-maximized")
    options.add_argument("--disable-infobars")
    driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    driver.get(tipo)
    precio= autos = driver.find_elements_by_xpath('//*[@id="listadocoches"]')
    cochesBuenos= [e.text for e in precio]
    for e in cochesBuenos:
        ok=e.split("\n")
    droplist=['Previous','Next',"IVA deducible"]
    cleanList=[e for e in ok if e not in droplist]
    CleanList=[]
    for e in cleanList:
        if not "desde" in e:
             CleanList.append(e)
    priceWithoutDiscount=CleanList[0::4]
    priceWithDiscount=CleanList[1::4]
    model=CleanList[2::4]
    cleanColumn=CleanList[3::4]
    for e in cleanColumn:
        ok=e.split("\n")
    cleanColumn2=[e.split("\n") for e in cleanColumn]
    ok2=[]
    for e in cleanColumn2:
        for i in e:
            ok2.append(i.split())
    Año=[e[0] for e in ok2]
    combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
    combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
    combustible=[item for sublist in combustiblesucio for item in sublist]
    gas=[]
    for e in combustible:
        if e == 'Hibrido':
            gas.append(e)
        elif e == "Diesel":
            gas.append(e)
        elif e == "Gasolina":
            gas.append(e)
        elif e == "Electrico":
            gas.append(e)
        elif e == "GLP":
            gas.append(e)
    df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })
    df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
    result = pd.concat([df, df1], axis=1, sort=False)
    flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
    def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan
    np_concat = np.vectorize(concat)
    flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
    flexicar = flexicar.drop(['nan'], axis=1)
    
    
    return flexicar.sort_values(by='Año', ascending=[True])

In [ ]:
FlexicarScraping(Tipo2)

In [ ]:
def flexicar_scraping(tipo):
    #URL=f'https://www.flexicar.es/coches-segunda-mano/#precio_to/{presupuesto}/'
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("start-maximized")
    options.add_argument("--disable-infobars")
    driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    driver.get(tipo)
    precio= autos = driver.find_elements_by_xpath('//*[@id="listadocoches"]')
    return precio

In [ ]:
def clean_data(listascraping):
    cochesBuenos= [e.text for e in precio]
    for e in cochesBuenos:
        ok=e.split("\n")
    droplist=['Previous','Next',"IVA deducible"]
    cleanList=[e for e in ok if e not in droplist]
    CleanList=[]
    for e in cleanList:
        if not "desde" in e:
             CleanList.append(e)
    priceWithoutDiscount=CleanList[0::4]
    priceWithDiscount=CleanList[1::4]
    model=CleanList[2::4]
    cleanColumn=CleanList[3::4]
    for e in cleanColumn:
        ok=e.split("\n")
    cleanColumn2=[e.split("\n") for e in cleanColumn]
    ok2=[]
    for e in cleanColumn2:
        for i in e:
            ok2.append(i.split())
    Año=[e[0] for e in ok2]
    combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
    combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
    combustible=[item for sublist in combustiblesucio for item in sublist]
    gas=[]
    for e in combustible:
        if e == 'Hibrido':
            gas.append(e)
        elif e == "Diesel":
            gas.append(e)
        elif e == "Gasolina":
            gas.append(e)
        elif e == "Electrico":
            gas.append(e)
        elif e == "GLP":
            gas.append(e)
    df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })
    df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
    result = pd.concat([df, df1], axis=1, sort=False)
    flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
    def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan
    np_concat = np.vectorize(concat)
    flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
    flexicar = flexicar.drop(['nan'], axis=1)
    
    
    return flexicar.sort_values(by='Año', ascending=[True])

In [ ]:
def pipeline_flexicar(tipo):
    x=FlexicarScraping(tipo)
    y= clean_data(x)
    cs.send("SEND " + FILE)
    cs.close()
    return y

In [ ]:
pipeline_flexicar(Tipo1)

In [ ]:
def mult():
    return 2*1

In [ ]:
mult()

# Argumentos

## Tipo de usuarios:

   ## Usuario Tipo 1 no: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 80% y 20% Extra-Urbanas.
   ### Conviviendo sólo o con un miembro más.
   
  Tipo1="https://www.flexicar.es/combustible-gasolina/carroceria-compacto/segunda-mano/"
  
  ## Usuario Tipo 2si: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 60% y 40% Extra-Urbanas.
   ### Conviviendo sólo o con un miembro más.
   
  Tipo2="https://www.flexicar.es/combustible-gasolina/carroceria-turismo/segunda-mano/"
  
   ## Usuario Tipo 3 no: 
   ### Persona que realiza más de 15.000km al año.
   ### Uso en vías Extra-Urbanas 80% y 20% Urbanas.
   ### Conviviendo sólo con un miembro más.
  Tipo3= 'https://www.flexicar.es/combustible-diesel/carroceria-turismo/segunda-mano/'
  
   ## Usuario Tipo 4 no : 
   ### Persona que realiza más de 15.000km al año.
   ### Uso en vías Extra-Urbanas 80% y 20% Urbanas.
   ### Familia con 1 o 2 hijos.
   Tipo4= "https://www.flexicar.es/combustible-diesel/carroceria-familiar/segunda-mano/"
   
   ## Usuario Tipo 5si: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 70% y 30% Extra-Urbanas.
   ### Familia con 1 o 2 hijos.
   Tipo5= "https://www.flexicar.es/combustible-gasolina/carroceria-familiar/segunda-mano/"
   
   ## Usuario Tipo 6a medias: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 60% y 40% Extra-Urbanas.
   ### Familia con más de 2 hijos.
   Tipo6= "https://www.flexicar.es/combustible-gasolina/carroceria-monovolumen/segunda-mano/"
   
   ## Usuario Tipo 7 a medias: 
   ### Persona que realiza más de 15.000km al año.
   ### Uso en vías Extra-Urbanas 80% y 20% Urbanas.
   ### Familia con más de 2 hijos.
   Tipo7= "https://www.flexicar.es/combustible-diesel/carroceria-monovolumen/segunda-mano/"
   
   
   
  Tipo8='https://www.flexicar.es/combustible-diesel/carroceria-furgoneta/segunda-mano/#plazas/8/'