In [6]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import pandas as pd
import numpy as np
import re

In [61]:
options = webdriver.ChromeOptions()
options.add_argument("--headless")
options.add_argument("start-maximized")
options.add_argument("--disable-infobars")
driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
URL= "https://www.canalcar.es/coches-ocasion/berlina-segunda-mano-madrid/gasolina"
driver.get(URL)

In [62]:
precio= autos = driver.find_elements_by_xpath('//*[@id="madrid"]/div[2]/div[2]')
precio

In [63]:
cochesBuenos= [e.text for e in precio]
cochesBuenos

['-266€\nAUDI A4 2.0 TFSI 180cv multitronic\n13.290 €\n2011 131.881 Km Gasolina Automático\n-1.295€\nBMW 114 i 102CV\n12.950 €\n2014 85.861 Km Gasolina Manual\nBMW 318 i 129 CV\n6.990 €\n2006 160.739 Km Gasolina Automático\nBMW 320 i 150CV\n6.950 €\n2007 263.947 Km Gasolina Manual\n-1.434€\nBMW 520 iA 184CV\n20.490 €\n2013 56.653 Km Gasolina Automático\n-109€\nCHEVROLET Cruze 1.6 LS+ Clima 124CV\n5.450 €\n2011 170.994 Km Gasolina Manual\nCHEVROLET Cruze 1.8 LTZ\n6.950 €\n2012 133.482 Km Gasolina Manual\nCITROEN C5 1.8i SX 117cv\n2.950 €\n2006 136.377 Km Gasolina Manual\n-1.299€\nMAZDA 3 2.0 GE MT Style Confort 120CV\n12.990 €\n2014 121.235 Km Gasolina Manual\nMERCEDES-BENZ C 180 K Sport Edition 105kW (143CV)\n5.990 €\n2006 123.312 Km Gasolina Manual\n-4.999€\nMERCEDES-BENZ S 500 455 CV\n49.990 €\n2014 66.596 Km Gasolina Automático\n-949€\nOPEL Astra 1.6 Selective 85 kW (115 CV\n9.490 €\n2015 82.070 Km Gasolina Manual\n-380€\nPEUGEOT 508 1.6 THP Active 156CV\n9.490 €\n2011 68.935 Km Gasolina Manual\nPEUGEOT 607 V6 Pack Automático Ebano\n4.690 €\n2006 106.272 Km Gasolina Automático\n-1.399€\nRENAULT Kadjar TCe Zen Energy\n13.990 €\n2015 87.657 Km Gasolina Manual\nSAAB 9-3 1.8 t Linear Sport sedán 150CV\n3.390 €\n2005 141.959 Km Gasolina Manual\nSEAT Leon 1.4 TSI FR 125CV\n15.490 €\n2018 35.943 Km Gasolina Manual\n-1.749€\nSKODA Octavia 1.0 TSI Ambition DSG 115CV\n17.490 €\n2019 2.844 Km Gasolina Automático\n-1.749€\nTOYOTA Avensis 1.8 147cv ADVANCE MultiDrive\n17.490 €\n2016 10.617 Km Gasolina Automático\nVOLKSWAGEN Golf 1.4 TSI Advance 90 kW (122 CV)\n6.990 €\n2010 152.520 Km Gasolina Manual']

In [58]:
for e in cochesBuenos:
    ok=e.split("\n")
ok

['16100€',
 'ZARAGOZA',
 'Renault Scenic TCe 130 Zen Energy (130 CV)',
 '18.090€',
 'Desde 254€/mes',
 'a 9 años',
 '06/201724.448 kmGasolinaManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1165€',
 'VALENCIA-ALZIRA',
 'Hyundai Tucson 1.7 CRDI (115CV)',
 '16.335€',
 '17.500€',
 'Desde 227€/mes',
 'a 9 años',
 '10/201667.634 kmDiéselManualLibro MantenimientoÚnico propietarioGarantía oficial: Octubre 2021',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-769€',
 'VALENCIA-ALZIRA',
 'Peugeot 2008 1.6 BlueHDI Style (100CV)',
 '10.981€',
 '11.750€',
 'Desde 156€/mes',
 'a 8 años',
 '03/201640.882 kmDiéselManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Mercedes-Benz Clase S 320 CDI AUTO (204 CV)',
 '4.900€',
 '04/2005325.476 kmDiéselAutomático',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Volkswagen Polo 1.4 Advance (75 CV)',
 '3.600€',
 '07/200584.721 kmGasolinaManualLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-867€',
 'MÓSTOLES-VILLAVICIOSA',
 'Opel Mokka 1.6 CDTi Selective 4x2 Auto (136 CV)',
 '12.383€',
 '13.250€',
 'Desde 179€/mes',
 'a 8 años',
 '11/201581.419 kmDiéselAutomáticoLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-2205€',
 'MÓSTOLES-VILLAVICIOSA',
 'Peugeot 3008 1.6L THP Allure EAT6 (165 CV)',
 '22.045€',
 '24.250€',
 'Desde 296€/mes',
 'a 10 años',
 '06/201821.459 kmGasolinaAutomáticoLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1791€',
 'MÓSTOLES-VILLAVICIOSA',
 'Ford Transit 310 L2H2 Van Ambiente Delantera (130CV)',
 '17.909€',
 '19.700€',
 'Desde 237€/mes',
 'a 10 años',
 '11/201910.890 kmDiéselManualÚnico propietarioGarantía oficial: Noviembre 2021',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'Ford Fiesta 1.5 TDCI Trend (75 CV)',
 '6.591€',
 '7.250€',
 'Desde 79€/mes',
 'a 9 años',
 '03/2017118.413 kmDiéselManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-556€',
 'GETAFE',
 'Dacia Sandero 1.5 dCi Ambiance (75 CV)',
 '7.944€',
 '8.500€',
 'Desde 99€/mes',
 'a 9 años',
 '12/201615.444 kmDiéselManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'Opel Insignia 1.6 CDTI Start & Stop Selective (120 CV)',
 '9.159€',
 '9.800€',
 'Desde 126€/mes',
 'a 8 años',
 '03/2016124.161 kmDiéselManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Citroen Nemo 1.4 HDI (75 CV)',
 '4.350€',
 'Desde 116€/mes',
 'a 4 años',
 '02/2012143.040 kmDiéselManualLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1001€',
 'GETAFE',
 'Renault Megane dCi 110 GT Line Energy (110 CV)',
 '14.299€',
 '15.300€',
 'Desde 196€/mes',
 'a 9 años',
 '11/201671.599 kmDiéselManualLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'BMW Serie 3 318d xDrive Touring (150CV)',
 '16.168€',
 '17.300€',
 'Desde 240€/mes',
 'a 8 años',
 '07/2016120.008 kmDiéselManualLibro MantenimientoÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'VALENCIA-ALZIRA',
 'Ford Transit TOURNEO LX 2.5D (76CV)',
 '1.900€',
 '05/1995245.630 kmDiéselManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Peugeot 307 1.6 HDI X-Line (90cv)',
 '1.100€',
 '04/2006373.764 kmDiéselManualLibro Mantenimiento',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Peugeot 307 SW 1.6 HDI Port Aventura (110 CV)',
 '1.200€',
 '02/2005291.513 kmDiéselManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Peugeot 206 CC Cabrio 1.6 (110CV)',
 '4.700€',
 '03/2006103.502 kmGasolinaManual',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Audi A4 1.8 (125 CV)',
 '900€',
 '07/1997163.778 kmGasolinaManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Renault Modus 1.2 16v Emotion (75CV)',
 '4.500€',
 '01/200877.058 kmGasolinaManualÚnico propietario',
 'Contactar',
 'VER DE UN VISTAZO',
 'COMPARAR']

In [59]:
droplist=['Previous',
 'Next','Contactar',]

cleanList=[e for e in ok if e not in droplist]
cleanList

['16100€',
 'ZARAGOZA',
 'Renault Scenic TCe 130 Zen Energy (130 CV)',
 '18.090€',
 'Desde 254€/mes',
 'a 9 años',
 '06/201724.448 kmGasolinaManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1165€',
 'VALENCIA-ALZIRA',
 'Hyundai Tucson 1.7 CRDI (115CV)',
 '16.335€',
 '17.500€',
 'Desde 227€/mes',
 'a 9 años',
 '10/201667.634 kmDiéselManualLibro MantenimientoÚnico propietarioGarantía oficial: Octubre 2021',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-769€',
 'VALENCIA-ALZIRA',
 'Peugeot 2008 1.6 BlueHDI Style (100CV)',
 '10.981€',
 '11.750€',
 'Desde 156€/mes',
 'a 8 años',
 '03/201640.882 kmDiéselManualLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Mercedes-Benz Clase S 320 CDI AUTO (204 CV)',
 '4.900€',
 '04/2005325.476 kmDiéselAutomático',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Volkswagen Polo 1.4 Advance (75 CV)',
 '3.600€',
 '07/200584.721 kmGasolinaManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-867€',
 'MÓSTOLES-VILLAVICIOSA',
 'Opel Mokka 1.6 CDTi Selective 4x2 Auto (136 CV)',
 '12.383€',
 '13.250€',
 'Desde 179€/mes',
 'a 8 años',
 '11/201581.419 kmDiéselAutomáticoLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-2205€',
 'MÓSTOLES-VILLAVICIOSA',
 'Peugeot 3008 1.6L THP Allure EAT6 (165 CV)',
 '22.045€',
 '24.250€',
 'Desde 296€/mes',
 'a 10 años',
 '06/201821.459 kmGasolinaAutomáticoLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1791€',
 'MÓSTOLES-VILLAVICIOSA',
 'Ford Transit 310 L2H2 Van Ambiente Delantera (130CV)',
 '17.909€',
 '19.700€',
 'Desde 237€/mes',
 'a 10 años',
 '11/201910.890 kmDiéselManualÚnico propietarioGarantía oficial: Noviembre 2021',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'Ford Fiesta 1.5 TDCI Trend (75 CV)',
 '6.591€',
 '7.250€',
 'Desde 79€/mes',
 'a 9 años',
 '03/2017118.413 kmDiéselManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-556€',
 'GETAFE',
 'Dacia Sandero 1.5 dCi Ambiance (75 CV)',
 '7.944€',
 '8.500€',
 'Desde 99€/mes',
 'a 9 años',
 '12/201615.444 kmDiéselManualLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'Opel Insignia 1.6 CDTI Start & Stop Selective (120 CV)',
 '9.159€',
 '9.800€',
 'Desde 126€/mes',
 'a 8 años',
 '03/2016124.161 kmDiéselManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Citroen Nemo 1.4 HDI (75 CV)',
 '4.350€',
 'Desde 116€/mes',
 'a 4 años',
 '02/2012143.040 kmDiéselManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1001€',
 'GETAFE',
 'Renault Megane dCi 110 GT Line Energy (110 CV)',
 '14.299€',
 '15.300€',
 'Desde 196€/mes',
 'a 9 años',
 '11/201671.599 kmDiéselManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'BMW Serie 3 318d xDrive Touring (150CV)',
 '16.168€',
 '17.300€',
 'Desde 240€/mes',
 'a 8 años',
 '07/2016120.008 kmDiéselManualLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'VALENCIA-ALZIRA',
 'Ford Transit TOURNEO LX 2.5D (76CV)',
 '1.900€',
 '05/1995245.630 kmDiéselManual',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Peugeot 307 1.6 HDI X-Line (90cv)',
 '1.100€',
 '04/2006373.764 kmDiéselManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Peugeot 307 SW 1.6 HDI Port Aventura (110 CV)',
 '1.200€',
 '02/2005291.513 kmDiéselManual',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Peugeot 206 CC Cabrio 1.6 (110CV)',
 '4.700€',
 '03/2006103.502 kmGasolinaManual',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Audi A4 1.8 (125 CV)',
 '900€',
 '07/1997163.778 kmGasolinaManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Renault Modus 1.2 16v Emotion (75CV)',
 '4.500€',
 '01/200877.058 kmGasolinaManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR']

In [60]:
CleanList=[]

for e in cleanList:
    if not "Desde" in e:
             CleanList.append(e)       
CleanList

['16100€',
 'ZARAGOZA',
 'Renault Scenic TCe 130 Zen Energy (130 CV)',
 '18.090€',
 'a 9 años',
 '06/201724.448 kmGasolinaManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1165€',
 'VALENCIA-ALZIRA',
 'Hyundai Tucson 1.7 CRDI (115CV)',
 '16.335€',
 '17.500€',
 'a 9 años',
 '10/201667.634 kmDiéselManualLibro MantenimientoÚnico propietarioGarantía oficial: Octubre 2021',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-769€',
 'VALENCIA-ALZIRA',
 'Peugeot 2008 1.6 BlueHDI Style (100CV)',
 '10.981€',
 '11.750€',
 'a 8 años',
 '03/201640.882 kmDiéselManualLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Mercedes-Benz Clase S 320 CDI AUTO (204 CV)',
 '4.900€',
 '04/2005325.476 kmDiéselAutomático',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Volkswagen Polo 1.4 Advance (75 CV)',
 '3.600€',
 '07/200584.721 kmGasolinaManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-867€',
 'MÓSTOLES-VILLAVICIOSA',
 'Opel Mokka 1.6 CDTi Selective 4x2 Auto (136 CV)',
 '12.383€',
 '13.250€',
 'a 8 años',
 '11/201581.419 kmDiéselAutomáticoLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-2205€',
 'MÓSTOLES-VILLAVICIOSA',
 'Peugeot 3008 1.6L THP Allure EAT6 (165 CV)',
 '22.045€',
 '24.250€',
 'a 10 años',
 '06/201821.459 kmGasolinaAutomáticoLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1791€',
 'MÓSTOLES-VILLAVICIOSA',
 'Ford Transit 310 L2H2 Van Ambiente Delantera (130CV)',
 '17.909€',
 '19.700€',
 'a 10 años',
 '11/201910.890 kmDiéselManualÚnico propietarioGarantía oficial: Noviembre 2021',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'Ford Fiesta 1.5 TDCI Trend (75 CV)',
 '6.591€',
 '7.250€',
 'a 9 años',
 '03/2017118.413 kmDiéselManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-556€',
 'GETAFE',
 'Dacia Sandero 1.5 dCi Ambiance (75 CV)',
 '7.944€',
 '8.500€',
 'a 9 años',
 '12/201615.444 kmDiéselManualLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'Opel Insignia 1.6 CDTI Start & Stop Selective (120 CV)',
 '9.159€',
 '9.800€',
 'a 8 años',
 '03/2016124.161 kmDiéselManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'GETAFE',
 'Citroen Nemo 1.4 HDI (75 CV)',
 '4.350€',
 'a 4 años',
 '02/2012143.040 kmDiéselManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 '-1001€',
 'GETAFE',
 'Renault Megane dCi 110 GT Line Energy (110 CV)',
 '14.299€',
 '15.300€',
 'a 9 años',
 '11/201671.599 kmDiéselManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'IVA DEDUCIBLE',
 'GETAFE',
 'BMW Serie 3 318d xDrive Touring (150CV)',
 '16.168€',
 '17.300€',
 'a 8 años',
 '07/2016120.008 kmDiéselManualLibro MantenimientoÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'VALENCIA-ALZIRA',
 'Ford Transit TOURNEO LX 2.5D (76CV)',
 '1.900€',
 '05/1995245.630 kmDiéselManual',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Peugeot 307 1.6 HDI X-Line (90cv)',
 '1.100€',
 '04/2006373.764 kmDiéselManualLibro Mantenimiento',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'ZARAGOZA',
 'Peugeot 307 SW 1.6 HDI Port Aventura (110 CV)',
 '1.200€',
 '02/2005291.513 kmDiéselManual',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Peugeot 206 CC Cabrio 1.6 (110CV)',
 '4.700€',
 '03/2006103.502 kmGasolinaManual',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Audi A4 1.8 (125 CV)',
 '900€',
 '07/1997163.778 kmGasolinaManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR',
 'COLLADO-VILLALBA',
 'Renault Modus 1.2 16v Emotion (75CV)',
 '4.500€',
 '01/200877.058 kmGasolinaManualÚnico propietario',
 'VER DE UN VISTAZO',
 'COMPARAR']

In [13]:
CleanList[0:4]

['19.900€',
 '17.900€',
 'Renault Scenic Zen TCe 103kW (140CV) EDC GPF',
 '2019 12.587 kmGasolina Rivas II']

In [14]:
priceWithoutDiscount=CleanList[0::4]
priceWithDiscount=CleanList[1::4]
model=CleanList[2::4]
cleanColumn=CleanList[3::4]

cleanColumn

['2019 12.587 kmGasolina Rivas II',
 '2015 28.611 kmGasolina Móstoles 2',
 '2004 180.400 kmGasolina',
 '2016 42.150 kmGasolina Leganés',
 '2016 55.000 kmGasolina San Sebastián De Los Reyes',
 '2018 31.000 kmGasolina Alicante',
 '2016 26.000 kmGasolina Badalona',
 '2011 105.000 kmGasolina Valladolid',
 '2011 99.999 kmGasolina Málaga']

In [15]:
for e in cleanColumn:
    ok=e.split("\n")
cleanColumn2=[e.split("\n") for e in cleanColumn]
ok2=[]
for e in cleanColumn2:
    for i in e:
         ok2.append(i.split())
Año=[e[0] for e in ok2]

Año

['2019', '2015', '2004', '2016', '2016', '2018', '2016', '2011', '2011']

In [30]:
Año=[e[0] for e in ok2]
Año

['2019', '2015', '2004', '2016', '2016', '2018', '2016', '2011', '2011']

In [16]:
for e in cleanColumn:
    ok=e.split("\n")
cleanColumn2=[e.split("\n") for e in cleanColumn]
ok2=[]
for e in cleanColumn2:
    for i in e:
         ok2.append(i.split())
Combustible=[e[2] for e in ok2]

Combustible

['kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina']

In [31]:
Combustible=[e[2] for e in ok2]

Combustible

['kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina',
 'kmGasolina']

In [17]:
#Limpiando columna combustible
combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
combustiblesucio

[['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina'],
 ['Gasolina', 'asolina']]

In [18]:
combustible=[item for sublist in combustiblesucio for item in sublist]
gas=[]

for e in combustible:
    if e == 'Hibrido':
        gas.append(e)
    elif e == "Diesel":
        gas.append(e)
    elif e == "Gasolina":
        gas.append(e)
    elif e == "Electrico":
        gas.append(e) 
gas

['Gasolina',
 'Gasolina',
 'Gasolina',
 'Gasolina',
 'Gasolina',
 'Gasolina',
 'Gasolina',
 'Gasolina',
 'Gasolina']

In [19]:
cleanColumn

['2019 12.587 kmGasolina Rivas II',
 '2015 28.611 kmGasolina Móstoles 2',
 '2004 180.400 kmGasolina',
 '2016 42.150 kmGasolina Leganés',
 '2016 55.000 kmGasolina San Sebastián De Los Reyes',
 '2018 31.000 kmGasolina Alicante',
 '2016 26.000 kmGasolina Badalona',
 '2011 105.000 kmGasolina Valladolid',
 '2011 99.999 kmGasolina Málaga']

In [20]:
df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })

In [21]:
print(len(gas), len(Año), len(cleanColumn),len(model),len(priceWithDiscount),len(priceWithoutDiscount))

9 9 9 9 9 9

In [22]:
df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
df1

   Año1       KM           3      Ciudad                     nan
0  2019   12.587  kmGasolina       Rivas                      II
1  2015   28.611  kmGasolina    Móstoles                       2
2  2004  180.400  kmGasolina        None                    None
3  2016   42.150  kmGasolina     Leganés                    None
4  2016   55.000  kmGasolina         San  Sebastián De Los Reyes
5  2018   31.000  kmGasolina    Alicante                    None
6  2016   26.000  kmGasolina    Badalona                    None
7  2011  105.000  kmGasolina  Valladolid                    None
8  2011   99.999  kmGasolina      Málaga                    None

In [23]:
result = pd.concat([df, df1], axis=1, sort=False)
result

,priceWithDiscount,Model,Combustible,Año,cleanToSplit,Año1,KM,3,Ciudad,nan
0,17.900€,Renault Scenic Zen TCe 103kW (140CV) EDC GPF,Gasolina,2019,2019 12.587 kmGasolina Rivas II,2019,12.587,kmGasolina,Rivas,II
1,10.490€,Ford C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2015,2015 28.611 kmGasolina Móstoles 2,2015,28.611,kmGasolina,Móstoles,2
2,3.490€,Renault Scenic LUXE PRIVILEGE 1.6 16V,Gasolina,2004,2004 180.400 kmGasolina,2004,180.400,kmGasolina,None,None
3,12.490€,Ford Grand C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2016,2016 42.150 kmGasolina Leganés,2016,42.150,kmGasolina,Leganés,None
4,13.990€,Volkswagen Touran Edition 1.2 TSI 110CV BMT,Gasolina,2016,2016 55.000 kmGasolina San Sebastián De Los Reyes,2016,55.000,kmGasolina,San,Sebastián De Los Reyes
5,14.990€,Citroen Grand C4 Spacetourer PureTech 96KW (13...,Gasolina,2018,2018 31.000 kmGasolina Alicante,2018,31.000,kmGasolina,Alicante,None
6,9.990€,Dacia Dokker Ambiance 1.6 100cv EU6 2016,Gasolina,2016,2016 26.000 kmGasolina Badalona,2016,26.000,kmGasolina,Badalona,None
7,6.990€,Citroen C4 Picasso 1.6 VTi 120cv Seduction,Gasolina,2011,2011 105.000 kmGasolina Valladolid,2011,105.000,kmGasolina,Valladolid,None
8,6.990€,Peugeot 5008 Confort 1.6 VTi 120,Gasolina,2011,2011 99.999 kmGasolina Málaga,2011,99.999,kmGasolina,Málaga,None

In [24]:
flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
flexicar

,priceWithDiscount,Model,Combustible,Año,KM,Ciudad,nan
0,17.900€,Renault Scenic Zen TCe 103kW (140CV) EDC GPF,Gasolina,2019,12.587,Rivas,II
1,10.490€,Ford C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2015,28.611,Móstoles,2
2,3.490€,Renault Scenic LUXE PRIVILEGE 1.6 16V,Gasolina,2004,180.400,None,None
3,12.490€,Ford Grand C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2016,42.150,Leganés,None
4,13.990€,Volkswagen Touran Edition 1.2 TSI 110CV BMT,Gasolina,2016,55.000,San,Sebastián De Los Reyes
5,14.990€,Citroen Grand C4 Spacetourer PureTech 96KW (13...,Gasolina,2018,31.000,Alicante,None
6,9.990€,Dacia Dokker Ambiance 1.6 100cv EU6 2016,Gasolina,2016,26.000,Badalona,None
7,6.990€,Citroen C4 Picasso 1.6 VTi 120cv Seduction,Gasolina,2011,105.000,Valladolid,None
8,6.990€,Peugeot 5008 Confort 1.6 VTi 120,Gasolina,2011,99.999,Málaga,None

In [25]:
def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan
np_concat = np.vectorize(concat)
np_concat(flexicar['Ciudad'],flexicar['nan'])

array(['Rivas,II', 'Móstoles,2', 'nan', 'Leganés',
       'San,Sebastián De Los Reyes', 'Alicante', 'Badalona', 'Valladolid',
       'Málaga'], dtype='<U26')

In [26]:
flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
flexicar

,priceWithDiscount,Model,Combustible,Año,KM,Ciudad,nan
0,17.900€,Renault Scenic Zen TCe 103kW (140CV) EDC GPF,Gasolina,2019,12.587,"Rivas,II",II
1,10.490€,Ford C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2015,28.611,"Móstoles,2",2
2,3.490€,Renault Scenic LUXE PRIVILEGE 1.6 16V,Gasolina,2004,180.400,nan,None
3,12.490€,Ford Grand C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2016,42.150,Leganés,None
4,13.990€,Volkswagen Touran Edition 1.2 TSI 110CV BMT,Gasolina,2016,55.000,"San,Sebastián De Los Reyes",Sebastián De Los Reyes
5,14.990€,Citroen Grand C4 Spacetourer PureTech 96KW (13...,Gasolina,2018,31.000,Alicante,None
6,9.990€,Dacia Dokker Ambiance 1.6 100cv EU6 2016,Gasolina,2016,26.000,Badalona,None
7,6.990€,Citroen C4 Picasso 1.6 VTi 120cv Seduction,Gasolina,2011,105.000,Valladolid,None
8,6.990€,Peugeot 5008 Confort 1.6 VTi 120,Gasolina,2011,99.999,Málaga,None

In [27]:
flexicar = flexicar.drop(['nan'], axis=1)
flexicar

,priceWithDiscount,Model,Combustible,Año,KM,Ciudad
0,17.900€,Renault Scenic Zen TCe 103kW (140CV) EDC GPF,Gasolina,2019,12.587,"Rivas,II"
1,10.490€,Ford C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2015,28.611,"Móstoles,2"
2,3.490€,Renault Scenic LUXE PRIVILEGE 1.6 16V,Gasolina,2004,180.400,nan
3,12.490€,Ford Grand C-Max 1.0 EcoBoost 125CV Titanium,Gasolina,2016,42.150,Leganés
4,13.990€,Volkswagen Touran Edition 1.2 TSI 110CV BMT,Gasolina,2016,55.000,"San,Sebastián De Los Reyes"
5,14.990€,Citroen Grand C4 Spacetourer PureTech 96KW (13...,Gasolina,2018,31.000,Alicante
6,9.990€,Dacia Dokker Ambiance 1.6 100cv EU6 2016,Gasolina,2016,26.000,Badalona
7,6.990€,Citroen C4 Picasso 1.6 VTi 120cv Seduction,Gasolina,2011,105.000,Valladolid
8,6.990€,Peugeot 5008 Confort 1.6 VTi 120,Gasolina,2011,99.999,Málaga

In [34]:
# Tipos de usuarios:

Tipo1="https://www.flexicar.es/combustible-gasolina/carroceria-compacto/segunda-mano/"
Tipo2= "https://www.flexicar.es/combustible-gasolina/carroceria-turismo/segunda-mano/"
Tipo3= "https://www.flexicar.es/combustible-diesel/carroceria-turismo/segunda-mano/"
Tipo4= "https://www.flexicar.es/combustible-diesel/carroceria-familiar/segunda-mano/"
Tipo5= "https://www.flexicar.es/combustible-gasolina/carroceria-familiar/segunda-mano/"
Tipo6= "https://www.flexicar.es/combustible-gasolina/carroceria-monovolumen/segunda-mano/"
Tipo7= "https://www.flexicar.es/combustible-diesel/carroceria-monovolumen/segunda-mano/"
Tipo8= "https://www.flexicar.es/combustible-diesel/carroceria-furgoneta/segunda-mano/#plazas/8/"

In [38]:
def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan

In [39]:
def FlexicarScraping(tipo):
    #URL=f'https://www.flexicar.es/coches-segunda-mano/#precio_to/{presupuesto}/'
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("start-maximized")
    options.add_argument("--disable-infobars")
    driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    driver.get(tipo)
    precio= autos = driver.find_elements_by_xpath('//*[@id="listadocoches"]')
    cochesBuenos= [e.text for e in precio]
    for e in cochesBuenos:
        ok=e.split("\n")
    droplist=['Previous','Next',"IVA deducible"]
    cleanList=[e for e in ok if e not in droplist]
    CleanList=[]
    for e in cleanList:
        if not "desde" in e:
             CleanList.append(e)
    priceWithoutDiscount=CleanList[0::4]
    priceWithDiscount=CleanList[1::4]
    model=CleanList[2::4]
    cleanColumn=CleanList[3::4]
    for e in cleanColumn:
        ok=e.split("\n")
    cleanColumn2=[e.split("\n") for e in cleanColumn]
    ok2=[]
    for e in cleanColumn2:
        for i in e:
            ok2.append(i.split())
    Año=[e[0] for e in ok2]
    Combustible=[e[2] for e in ok2]
    combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
    combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
    combustible=[item for sublist in combustiblesucio for item in sublist]
    gas=[]
    for e in combustible:
        if e == 'Hibrido':
            gas.append(e)
        elif e == "Diesel":
            gas.append(e)
        elif e == "Gasolina":
            gas.append(e)
        elif e == "Electrico":
            gas.append(e)
        elif e == "GLP":
            gas.append(e)
    df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })
    df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
    result = pd.concat([df, df1], axis=1, sort=False)
    flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
    np_concat = np.vectorize(concat)
    flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
    flexicar = flexicar.drop(['nan'], axis=1)
    
    
    return flexicar.sort_values(by='Año', ascending=[True])

In [41]:
FlexicarScraping("https://www.flexicar.es/combustible-gasolina/carroceria-turismo/segunda-mano/")

,priceWithDiscount,Model,Combustible,Año,KM,Ciudad
8,16.490€,Volkswagen Golf 3.2 R32 4motion,Gasolina,2002,205.000,nan
5,12.790€,Mini Countryman 1.6 Cooper S,Gasolina,2011,59.000,Alicante
3,4.990€,Citroen C3 1.1i Attraction,Gasolina,2012,130.000,Alicante
2,6.490€,Fiat 500 1.2 8v 69 CV Lounge EU6,Gasolina,2014,75.000,Vaciamadrid
4,7.690€,Renault Clio Expression 1.2 16v 75,Gasolina,2015,69.990,"Móstoles,2"
0,9.490€,Renault Clio Zen Energy TCe 66kW (90CV),Gasolina,2017,49.990,"Móstoles,2"
1,7.990€,Fiat 500 1.2 8v 51kW (69CV) Lounge,Gasolina,2017,49.990,Vaciamadrid
7,40.990€,Audi A5 sport 2.0 TFSI 140kW S tronic Sportback,Gasolina,2017,61.677,"Rivas,II"
6,15.490€,Volkswagen Polo Sport 1.0 TSI 85kW (115CV) DSG,Gasolina,2019,15.949,Bilbao

In [ ]:
def flexicar_scraping(tipo):
    #URL=f'https://www.flexicar.es/coches-segunda-mano/#precio_to/{presupuesto}/'
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("start-maximized")
    options.add_argument("--disable-infobars")
    driver = webdriver.Chrome(executable_path=r'/usr/bin/chromedriver',options=options) 
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
    driver.get(tipo)
    precio= autos = driver.find_elements_by_xpath('//*[@id="listadocoches"]')
    return precio

In [53]:
def clean_data(listascraping):
    cochesBuenos= [e.text for e in precio]
    for e in cochesBuenos:
        ok=e.split("\n")
    droplist=['Previous','Next',"IVA deducible"]
    cleanList=[e for e in ok if e not in droplist]
    CleanList=[]
    for e in cleanList:
        if not "desde" in e:
             CleanList.append(e)
    priceWithoutDiscount=CleanList[0::4]
    priceWithDiscount=CleanList[1::4]
    model=CleanList[2::4]
    cleanColumn=CleanList[3::4]
    for e in cleanColumn:
        ok=e.split("\n")
    cleanColumn2=[e.split("\n") for e in cleanColumn]
    ok2=[]
    for e in cleanColumn2:
        for i in e:
            ok2.append(i.split())
    Año=[e[0] for e in ok2]
    combustiblesucio=[re.findall(r"([$D-H](\w+))",e) for e in Combustible]
    combustiblesucio=[list(item) for sublist in combustiblesucio for item in sublist]
    combustible=[item for sublist in combustiblesucio for item in sublist]
    gas=[]
    for e in combustible:
        if e == 'Hibrido':
            gas.append(e)
        elif e == "Diesel":
            gas.append(e)
        elif e == "Gasolina":
            gas.append(e)
        elif e == "Electrico":
            gas.append(e)
        elif e == "GLP":
            gas.append(e)
    df = pd.DataFrame({
                   'priceWithDiscount': priceWithDiscount,
                     'Model' : model,
                     'Combustible': gas,
                     'Año': Año,
                     'cleanToSplit': cleanColumn
                  })
    df1 = pd.DataFrame(df.cleanToSplit.str.split(' ',4).tolist(),
                                 columns = ["Año1","KM","3","Ciudad","nan"])
    result = pd.concat([df, df1], axis=1, sort=False)
    flexicar = result.drop(["cleanToSplit",'Año1','3'], axis=1)
    def concat(*args):
        strs = [str(arg) for arg in args if not pd.isnull(arg)]
        return ','.join(strs) if strs else np.nan
    np_concat = np.vectorize(concat)
    flexicar['Ciudad'] = np_concat(flexicar['Ciudad'], flexicar['nan'])
    flexicar = flexicar.drop(['nan'], axis=1)
    
    
    return flexicar.sort_values(by='Año', ascending=[True])

In [59]:
def pipeline_flexicar(tipo):
    x=FlexicarScraping(tipo)
    y= clean_data(x)
    cs.send("SEND " + FILE)
    cs.close()
    return y

In [60]:
pipeline_flexicar(Tipo1)

MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=46427): Max retries exceeded with url: /session/12bb0500635efae5aecdbab131942ce7/element/0.38016909207554206-1/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f939ec770b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

In [ ]:
def mult():
    return 2*1

In [47]:
mult()

2

# Argumentos

## Tipo de usuarios:

   ## Usuario Tipo 1 no: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 80% y 20% Extra-Urbanas.
   ### Conviviendo sólo o con un miembro más.
   
  Tipo1="https://www.flexicar.es/combustible-gasolina/carroceria-compacto/segunda-mano/"
  
  ## Usuario Tipo 2si: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 60% y 40% Extra-Urbanas.
   ### Conviviendo sólo o con un miembro más.
   
  Tipo2="https://www.flexicar.es/combustible-gasolina/carroceria-turismo/segunda-mano/"
  
   ## Usuario Tipo 3 no: 
   ### Persona que realiza más de 15.000km al año.
   ### Uso en vías Extra-Urbanas 80% y 20% Urbanas.
   ### Conviviendo sólo con un miembro más.
  Tipo3= 'https://www.flexicar.es/combustible-diesel/carroceria-turismo/segunda-mano/'
  
   ## Usuario Tipo 4 no : 
   ### Persona que realiza más de 15.000km al año.
   ### Uso en vías Extra-Urbanas 80% y 20% Urbanas.
   ### Familia con 1 o 2 hijos.
   Tipo4= "https://www.flexicar.es/combustible-diesel/carroceria-familiar/segunda-mano/"
   
   ## Usuario Tipo 5si: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 70% y 30% Extra-Urbanas.
   ### Familia con 1 o 2 hijos.
   Tipo5= "https://www.flexicar.es/combustible-gasolina/carroceria-familiar/segunda-mano/"
   
   ## Usuario Tipo 6a medias: 
   ### Persona que realiza menos de 15.000km al año.
   ### Uso en vías Urbanas 60% y 40% Extra-Urbanas.
   ### Familia con más de 2 hijos.
   Tipo6= "https://www.flexicar.es/combustible-gasolina/carroceria-monovolumen/segunda-mano/"
   
   ## Usuario Tipo 7 a medias: 
   ### Persona que realiza más de 15.000km al año.
   ### Uso en vías Extra-Urbanas 80% y 20% Urbanas.
   ### Familia con más de 2 hijos.
   Tipo7= "https://www.flexicar.es/combustible-diesel/carroceria-monovolumen/segunda-mano/"
   
   
   
  Tipo8='https://www.flexicar.es/combustible-diesel/carroceria-furgoneta/segunda-mano/#plazas/8/'